name: whatsapp_clone
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5
  sliding_up_panel: ^2.0.0+1
  story_view: ^0.13.2
  provider: ^6.0.2
  flutter_colorpicker: ^1.0.3
  uuid: ^3.0.6
  percent_indicator: ^4.0.0
  google_fonts: ^2.3.1
  dotted_border: ^2.0.0+2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.7.0
  font_awesome_flutter: ^10.1.0
  share_plus: ^4.0.4
  path_provider: ^2.0.9



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_lints: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/settingPhoto/splah.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/settingPhoto/logo.png"


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  #flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/10.jpg
     - assets/20.jpg
     - assets/30.jpg
     - assets/40.jpg
     - assets/50.jpg
     - assets/60.jpg
     - assets/70.jpg
     - assets/80.jpg
     - assets/90.jpg
     - assets/100.jpg
     - assets/110.jpg
     - assets/120.jpg
     - assets/callBackground.jpg
     - assets/chatBack.jpg
     - assets/story1.jpg
     - assets/story2.jpg
     - assets/story3.jpg
     - assets/story4.jpg
     - assets/story5.jpg
     - assets/story6.jpg
     - assets/story7.jpg
     - assets/story8.jpg
     - assets/story9.jpg
     - assets/settingPhoto/img.png
     - assets/settingPhoto/meta_icon.png
     - assets/settingPhoto/wtsappIcon.png
     - assets/settingPhoto/splah.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
